[env:irec_2526_fcu]
platform = teensy
board = teensy41
framework = arduino
board_build.fcu_profile = irec_2526_fcu
extra_scripts = pre:../../tools/codegen/platformio_fcu_config.py
upload_protocol = teensy-cli
lib_deps =
    adafruit/Adafruit BMP5xx Library
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -I../..
    -I../../hal/include
    -I../../flight/include
