[env:dummy_uno_r3]
platform = atmelavr
board = uno
framework = arduino
board_build.fcu_profile = dummy_uno_r3
extra_scripts = pre:../../tools/codegen/platformio_fcu_config.py
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -I../..
    -I../../hal/include
    -I../../flight/include
